### ISSUE TITLE
Suggestion to change the section about JavaScript

### ISSUE THREAD

**Issue by hzoo** [grab/front-end-guide#149]
For https://github.com/grab/front-end-guide#new-age-javascript, can you mention using https://github.com/babel/babel-preset-env instead of "ES2015" by which you mean babel-preset-es2015? I would explain that as browsers natively support ES whatever babel can just compile what is necessary.

And regarding babel-preset-stage-0, I would recommend explaining what Stage 0 means if it's going to be mentioned at all (that it's not javascript and just proposals that might go away). If you need help with this, can check out http://babeljs.io/docs/plugins/#presets-stage-x-experimental-presets-, https://github.com/hzoo/role-of-babel-in-js, https://tc39.github.io/process-document/

**Comment by yangshun** [comment]
Thanks for the suggestions @hzoo . Will get to it immediately.

**Comment by sidhuko** [comment]
I would recommend suggesting stage-3 for stability. Historically, stage-0 implementations have changed their implementations, async/await was a big one, where as a stage-3 is basically just awaiting implementation. 

Although you could probably write a [codemod ](https://github.com/facebook/codemod) to change them nowadays.

**Comment by yangshun** [comment]
Thanks for your comments @sidhuko , but the fact is that we were using preset-stage-0, and are in the process of changing to preset-env for our apps. I'll add in a note to inform about using stage-3 for stability.

**Comment by hzoo** [comment]
Yeah Stage 0 is literally just someone's idea on the committee and could change at any point. Of course we have tests and will try to help migrate users when possible but we are just volunteers.

**Comment by yangshun** [comment]
Thanks for everyone's comments. Fixed in 4571a88.
