### ISSUE TITLE
Error monitoring

### ISSUE THREAD

**Issue by justrossthings** [grab/front-end-guide#151]
How do you handle errors in your front-end application? Eg. https://sentry.io/

**Comment by yangshun** [comment]
Yes, we do use Sentry.io. Ok I'll think about including a short section on that 😄

**Comment by sujono91** [comment]
@yangshun if you don't mind, what kind of message that u send to sentry? Do you use redux middleware like [Raven for Redux](https://github.com/captbaritone/raven-for-redux) to send its state?

**Comment by paradite** [comment]
Hi @sujono91, we use https://github.com/getsentry/raven-js to send error to sentry.

**Comment by sujono91** [comment]
@paradite oh, so you don't send the current redux state when you got a JS error?
