### ISSUE TITLE
Possible mention of prettier

### ISSUE THREAD

**Issue by rparkisoniii** [grab/front-end-guide#155]
Because you mention Airbnb's javascript style guidelines, I think pointing users to  [prettier](https://github.com/prettier/prettier) would be useful. It's reasonably painful to continually format your code and this automates the process. Also I believe Airbnb is using prettier now as well.

**Comment by yangshun** [comment]
I can add it as an alternative (:

**Comment by yangshun** [comment]
Closed in 4fb3afe
