### ISSUE TITLE
Tips on collaboration and maintainability 

### ISSUE THREAD

**Issue by vpanjganj** [grab/front-end-guide#161]
Hi, we have a set of [common practices](https://github.com/wearehive/project-guidelines) that can be useful for you readers. It suits your [maintainability intro](https://github.com/grab/front-end-guide#maintainability) and It doesn't have any collision with your content. I can make a PR if you're fine with it. 

Thanks

**Comment by yangshun** [comment]
Sure thing, thanks in advance!
