### ISSUE TITLE
React Fundamentals is no longer free

### ISSUE THREAD

**Issue by Mohamed3on** [grab/front-end-guide#163]
Unfortunately, [its creator is no longer with React Training, and the course is no longer free](https://twitter.com/tylermcginnis33/status/884533130237005824).
I suggest it should be either removed or at least modified (note that it's not free and is not associated with React Training anymore).

**Comment by yangshun** [comment]
Thanks for the note, that's really unfortunate. I have changed it to an Egghead React course in 6c428c3.
