### ISSUE TITLE
Prettier is not an alternative for ESLint

### ISSUE THREAD

**Issue by rqrqrqrq** [grab/front-end-guide#164]
There is a common misconception about prettier and eslint. Prettier only maintains code style, but eslint maintains style + logic. For the most cases it's useful to setup them to work together.

I think we should not show to learners that these tools do the same. Prettier is definitely not an alternative to eslint and cannot replace it.

**Comment by paradite** [comment]
Fixed via https://github.com/grab/front-end-guide/pull/165, thanks!
